/*
 * This source file was generated by the Gradle 'init' task
 */
package org.pdfHtmlConverter;

import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(true);
    }
}
